trigger:
- none

pool:
  name: datasynchro-pool-ado
  demands:
  - ImageOverride -equals windows-2022

 

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: Bash@3
  displayName: List Directory Contents
  enabled: false
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      ls $(System.DefaultWorkingDirectory)

- task: NodeTool@0
  displayName: 'Use Node.js 22'
  inputs:
    versionSpec: '22.x'  # Use latest available Node.js 22 version


- script: node -v
  displayName: 'Check Node.js Version'


- script: npm install
  displayName: 'Install Dependencies'
  workingDirectory: '$(Build.SourcesDirectory)/web-app'
- task: Npm@1
  displayName: npm install
  inputs:
    command: 'install'
    workingDir: '$(Build.SourcesDirectory)/web-app'
- task: Npm@1
  displayName: npm buil
  inputs:
    command: 'custom'
    customCommand: 'run build'
    workingDir: '$(Build.SourcesDirectory)/web-app'